### ISSUE TITLE
docker build 时, 执行到第7步报错 , 提示权限不足

### ISSUE THREAD

**Issue by jaxwang** [shfshanyue/wechat-chatgpt#4]
linux ubuntu 20.04
使用docker build时报错, 
```
Step 7/9 : RUN pnpm i
 ---> Running in e9b6fcb166d2
 EACCES  EACCES: permission denied, open '/code/_tmp_7_ab1dbaa0bd09b4f84737b17c208a8dc2'



ERROR: Service 'wechat-chatgpt' failed to build : The command '/bin/sh -c pnpm i' returned a non-zero code: 1

```

docker-compose.yml  加 `privileged: true`  依然如此

**Comment by 1328449337** [comment]
您好～邮件我已收到，我将尽快查阅。

**Comment by jaxwang** [comment]
我把dockerfile第7行的 `USER 1000` 删掉就可以了.

**Comment by shfshanyue** [comment]
代码是不是不是最新的啊

**Comment by jaxwang** [comment]
> 代码是不是不是最新的啊

应该是最新的 , 我刚刚clone,  master分支.    dockerfile 中  使用 `USER 0` 用root用户构建应该也没啥问题吧. 我把`USER 1000`去掉了, 保留了`USER 0`

**Comment by shfshanyue** [comment]
嗯嗯，我跑着没有问题

> > 代码是不是不是最新的啊
> 
> 应该是最新的 , 我刚刚clone, master分支. dockerfile 中 使用 `USER 0` 用root用户构建应该也没啥问题吧. 我把`USER 1000`去掉了, 保留了`USER 0`

嗯嗯，我跑着没有问题，最终构建的镜像最好不要是 root，有安全问题
