### ISSUE TITLE
安装完成后跟机器人聊天报错Number of attempts exceeded

### ISSUE THREAD

**Issue by ccsc006** [shfshanyue/wechat-chatgpt#5]
扫码成功登录，/ping 后回复pong正常。但是聊天时候 总是回复"抱歉，我发生了一点小意外。" .终端是 " Number of attempts exceeded." 重新生成了API keys后也是如此。 测试环境是AWS上的弗吉尼亚北部站点，ubuntu 系统

**Comment by shfshanyue** [comment]
1. 看看 key 还有余额吗
2. 看看发送请求地址对不对

**Comment by ccsc006** [comment]
> 1. 看看 key 还有余额吗
> 2. 看看发送请求地址对不对

1.key 余额还有8刀了
2.发送的请求地址在哪里修改，我只是在.env里边加上了自己的api_key ,其他的都没有改过。

**Comment by shfshanyue** [comment]
> > 1. 看看 key 还有余额吗
> > 2. 看看发送请求地址对不对
> 
> 1.key 余额还有8刀了 2.发送的请求地址在哪里修改，我只是在.env里边加上了自己的api_key ,其他的都没有改过。

断点调试下发请求的接口那里吧
